name: pedantic
version: 1.9.1
description: >-
  The Dart analyzer settings and best practices used internally at Google.
homepage: https://github.com/dart-lang/pedantic

environment:
  sdk: '>=2.1.1 <3.0.0'

dependencies:
  meta: ^1.2.0
