name: pedantic
version: 1.8.0+1
description: How to get the most value from Dart static analysis.
author: Dart Team <misc@dartlang.org>
homepage: https://github.com/dart-lang/pedantic

environment:
  sdk: '>=2.1.1-dev.0.0 <3.0.0'
